# Generated by Django 3.0.1 on 2020-08-27 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_course', models.CharField(max_length=100)),
                ('grade_result', models.FloatField(blank=True, max_length=3, null=True)),
                ('feedback', models.TextField(blank=True, max_length=300, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(blank=True, max_length=50, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=50, null=True)),
                ('postcode', models.CharField(blank=True, max_length=8, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_birth', models.DateField(max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('guardian_first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('guardian_last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('guardian_relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('guardian_phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('grade_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='management.GradeClass')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
